### ISSUE TITLE
Bug: Unable to get property 'getBoundingClientRect' of undefined or null reference

### ISSUE THREAD

**Issue by joeybaker** [brigade/react-waypoint#116]
Running this in prod, we get somewhat frequent errors that look like the following:

![screen shot 2016-09-14 at 4 12 07 pm](https://cloud.githubusercontent.com/assets/36662/18533222/397b2c4e-7a96-11e6-854a-72f32d14b8fc.png)

I've not had the time to look into this, but a fix would be appreciated!

**Comment by jmeas** [comment]
Interesting. A quick workaround would be to bail out of the method if the ref doesn't exist at the time that it's called. But it would be good to know under what circumstances that situation arises, too — is it possible to avoid it altogether? Is it normal react behavior? I don't know the answers to these questions :)

**Comment by joeybaker** [comment]
I've not had the time to dig in to really know, but when I've seen ref problems like this in the past, I've gone the early `return` route. ¯\_(ツ)_/¯ it works!

**Comment by trotzig** [comment]
Thanks for the report @joeybaker. I'm puzzled by how this can occur. We only call `_getBounds` from the scroll handler, which we should be unregistering correctly. One theory I had was that the `ref` function is invoked prior to `componentWillUnmount` (which would leave `this._ref` being `null`) but [that theory turned out to be false](https://jsfiddle.net/69z2wepo/56241/). 

I think I'll take the pragmatic approach for now and simply implementing the bail-out solution suggested by @jmeas. I hate not fully understanding this though.

**Comment by trotzig** [comment]
I just released 3.1.2 with a fix for this. Thanks for helping out!

**Comment by joeybaker** [comment]
Thank you!

**Comment by jmeas** [comment]
Thanks @trotzig !
