### ISSUE TITLE
Warnings about using proptypes

### ISSUE THREAD

**Issue by XXChester** [brigade/react-waypoint#119]
I just installed the latest react and this NPM package in an application. The library works great, however, the console is flooded with these warnings:

```
application.self-8f8100c….js?body=1:1512 
Warning: You are manually calling a React.PropTypes validation function for the `debug` prop on `Waypoint`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
```

I am not sure how to get rid of these warnings as javascript is not my strong suite.

**Comment by trotzig** [comment]
Interesting, thanks for the heads-up! I believe this is not only related to the `debug` prop. It's probably because we assign a `propTypes` variable at the top (and not directly on `Waypoint.propTypes`. We can just get rid of the variable. If you want to take a stab at it, I'd be happy to accept a PR simply removing the variable declaration.

**Comment by trotzig** [comment]
I pushed a fix here: https://github.com/brigade/react-waypoint/commit/8c371c4aad000038341d2c2b8c3b4ecb73216b69

**Comment by trotzig** [comment]
I just pushed 3.1.3 with this fix. Let me know if the warnings don't go away!
