### ISSUE TITLE
Waypoint fires onload

### ISSUE THREAD

**Issue by mmdonaldson** [brigade/react-waypoint#138]
I've noticed a few other issues which relate back to waypoint firing if there is async code rendering the data before the waypoint.

Is anyone currently looking at a fix for this?

**Comment by jmeas** [comment]
@mmdonaldson , it would be difficult for there to be a generic "fix" for this that applies to every situation. For that reason, it's best to consider your specific situation and come up with the solution that works for you.

[This comment](https://github.com/brigade/react-waypoint/issues/43#issuecomment-255312842) describes one common solution for images of known height. Namely, setting the height of the image on the element, so that the image loading doesn't "push" content below it down.

If that solution doesn't work for you, then I'd be happy to work through other options if you could provide more information. What's loading asynchronously? Is it an image, or some other content on the page?

**Comment by mmdonaldson** [comment]
@jmeas Yeah it's a list of articles that loads asynchronously.

I won't know the height of the container so my quick fix has been to put a min height on it, otherwise the onLeave will fire on the page load.

**Comment by jmeas** [comment]
@mmdonaldson that sounds like a solid approach. Another idea would be to attach the Waypoint only after the data has loaded.

It sounds like you found a solution that works, so I'm going to close this issue for now. Let me know if you run into further issues, and we can reopen this and keep the conversation going.
