### ISSUE TITLE
`onLeave` isn't fired when `onPositionChange` does

### ISSUE THREAD

**Issue by halt-hammerzeit** [brigade/react-waypoint#155]
```js
        <Waypoint
          onPositionChange={position => console.log(position)}
          scrollableAncestor={typeof window !== 'undefined' && window}
          onEnter={this.showHeaderButtons}
          onLeave={this.hideHeaderButtons} />
```

`onLeave` fires when scrolling normally.
But when scrolled to the bottom of the page and then refreshing the page the browser scrolls to the bottom when the page has been loaded and while `onPositionChange` fires correctly with the `above` updated position `onLeave` doesn't get called at all.

**Comment by halt-hammerzeit** [comment]
(in case you're interested why do I use `scrollableAncestor` it's because of `react-sticky` for the sticky header)

**Comment by halt-hammerzeit** [comment]
So, the cause seems to be this code:

```js
    if (currentPosition === POSITIONS.inside) {
      this.props.onEnter.call(this, callbackArg);
    } else if (previousPosition === POSITIONS.inside) {
      this.props.onLeave.call(this, callbackArg);
    }
```

Obviously enough, when a page has just been refreshed there's no `previousPosition` therefore `onLeave` doesn't fire.
Is it the intended behaviour and this bug won't be ever fixed, or should that `else` condition be modified to:

```js
    if (currentPosition === POSITIONS.inside) {
      this.props.onEnter.call(this, callbackArg);
    } else if (!previousPosition || previousPosition === POSITIONS.inside) {
      this.props.onLeave.call(this, callbackArg);
    }
```

**Comment by jmeas** [comment]
@halt-hammerzeit , I believe this expected behavior with the current API of React Waypoint.

Your proposed solution solves your use case, but makes any and all waypoints that are mounted outside of the frame fire `onLeave`. That doesn't make much sense to me, and I think we would get many more issues if we changed it to function that way.

To me, the contract of `onLeave` is simply that it was once in the frame, and now it is no longer in the frame. If it is mounted outside of the frame, then `onLeave` shouldn't be called.

I believe the source of this problem is an incorrect assumption about the initial state of the web app. You are assuming that when your app is mounted, the page will always be scrolled to the very top of the page. This example here demonstrates that a browser could auto-scroll before the waypoint mounts.

With this knowledge, you should be able to write a workaround that works for your use case. If not, then perhaps something like an `onMount` callback could be added, which has the position of the waypoint at mount time. Then you could conditionally check if a waypoint that you assumed would start in-frame is starting out of frame.

I'm also seeing a similarity between this issue and this particular comment in the scrollspy thread: https://github.com/brigade/react-waypoint/issues/112#issuecomment-234811604 . They're not exactly the same, but it's possible that accepting children ( #152 ) could help with this.

**Comment by halt-hammerzeit** [comment]
Ok, thanks for the detailed answer.

I'll still with this workaround then, and anyone coming from Google can use it too, since it's 100% working in this scenario

**Comment by jmeas** [comment]
I'm curious to hear @lencioni 's and @trotzig 's take on this issue. They may be in favor of this change you're describing, or they might have other solutions that could help.

**Comment by halt-hammerzeit** [comment]
Well, they could introduce a React property for that, for example.
If they find that a common issue.

**Comment by trotzig** [comment]
While I understand that this is a little confusing, I think the assessment made by @jmeas is right. I appreciate you reporting your findings though @halt-hammerzeit, and for providing a workaround.

**Comment by lencioni** [comment]
Should we add some information to the readme about this?

**Comment by jmeas** [comment]
I was thinking that, @lencioni . I can PR a thing up later today, unless you'd like to take a stab at it.

**Comment by jmeas** [comment]
As an aside, I could be convinced of there being a callback as a prop that is fired immediately when the component mounts, which is passed the initial position. To implement this, we would need the callback prop to be called [after this line](https://github.com/brigade/react-waypoint/blob/0253185fd92f25a9f8692e6c098f98a0c72c4ec2/src/waypoint.jsx#L201).

An example API would be:

```jsx
<Waypoint
  onMount={initialPosition => console.log(`This waypoint mounted at ${initialPosition}`)}
  onEnter={this.onEnter}/>
```

I'm not convinced that we need this right now, but if someone could show that it:

1. enables them to do something they cannot do with a workaround
2. enables them to clean up a really messy workaround to be much cleaner

then I'd likely be :+1: for this new prop.
