### ISSUE TITLE
Does not fire onLeave if page opens scrolled

### ISSUE THREAD

**Issue by huston007** [brigade/react-waypoint#156]
1. Place <waypoint> at the top of the page
2. Listen to `onLeave`
3. Scroll page down
4. Refresh page

`onLeave` callback does not fire after refresh

**Comment by jmeas** [comment]
Hi @huston007 ! Thanks for the issue. Turns out, there's already an issue discussing this situation over at #155. Go ahead and read that thread, and you should be able to come up with a workaround. The tl;dr is that we think this is how Waypoint should behave given the contract of how `onLeave` behaves. If you disagree, go ahead and make a case over in #155 and we can keep the conversation going.

For now, I'm going to close this particular issue as a duplicate.

Thanks again!
