### ISSUE TITLE
Why not <MyComponent/> as a child?

### ISSUE THREAD

**Issue by t47io** [brigade/react-waypoint#159]
First of all, this is a great library!

I read from the README that:
```
If you do pass a child, it must be a single DOM Element (eg; a `<div>`) and not a Component Element (eg; `<MyComponent />`).
```

I wonder why? Would the following work?
```jsx
<Waypoint>
  <div>
    <MyComponent/>
  </div>
</Waypoint>
```

**Comment by jmeas** [comment]
> First of all, this is a great library!

Glad you like it!

> I wonder why?

A Waypoint with children is an interesting situation that you don't always run into in React: a parent (the Waypoint) needs to access some information about the child. Usually data-flows from top-to-bottom, so this is an inversion of that rule of thumb.

More specifically, the Waypoint need the dimensions of its children (in this case, a single child) so that it can track when it comes within [the boundaries](https://github.com/brigade/react-waypoint#offsets-and-boundaries).

In this library, we use `ref`s to access this information about the children's node, as you can see [here](https://github.com/brigade/react-waypoint/blob/66939d3ff4b83a33441846dd478c17ee2160ae8e/src/waypoint.jsx#L398-L405).

If we head over to [the documentation of ref's](https://facebook.github.io/react/docs/refs-and-the-dom.html#refs-and-functional-components), we can learn that:

> You may not use the ref attribute on functional components

Therefore, as I understand it, it's less about the children not being a Component, but more about it not being a _functional_ Component. If it's class-based, then based on how I understand the code, it should work as an immediate child.

> Would the following work?

Yup, that should always work.

**Comment by t47io** [comment]
Thank you for the answer. Very helpful~

**Comment by t47io** [comment]
Hi, a follow-up here as I tried to implement a scrollspy:
```
import React from 'react';
import Waypoint from 'react-waypoint';


const ScrollSpy = ({
  section = '',
  onUpdateScroll = () => {},
  children = undefined,
}) => {
  console.error(children);

  return (
  <Waypoint onEnter={() => onUpdateScroll(section)}>
    <div>
      {children}
    </div>
  </Waypoint>
);
};

ScrollSpy.propTypes = {
  section: React.PropTypes.string,
  onUpdateScroll: React.PropTypes.func,
  children: React.PropTypes.node,
};


export default ScrollSpy;
```

However, I only get a empty `<span />` on the page. Any ideas?

**Comment by t47io** [comment]
My bad, `package.json` has `^4.1.0`, wrong version......
