### ISSUE TITLE
CSS requirements?

### ISSUE THREAD

**Issue by zth** [brigade/react-waypoint#19]
Hi! First, thanks for a great React component! 

I have an issue that keeps coming back to me occasionally. Sometimes, I just cannot get the waypoint to fire as intended, no matter  what I do. I usually put the waypoint after/at the end of lists (to load more elements), but most of my implementations it simply doesn't work. Usually it fires on page load, regardless of where I put it, and then simply dont fire again no matter what I do. So, I wonder, are there any basic requirements that needs to be fulfilled for this to work? Are there any common issues you can think of that can cause the type of issues I'm having?

I'll post some code to, but I couldn't get it working as intended even when I mimicked the example code. Really weird!

Thanks in advance for your time!

**Comment by lencioni** [comment]
I don't think there are any special CSS requirements that need to be fulfilled for `<Waypoint>` to work. However, I doubt it would work if it was in a container that had `display: none;` on it or something like that. And, it needs to be the descendant of a scrollable ancestor (e.g. the `window` or a `<div>` with an `overflow` style that enables scrolling).

It's possible that there is something weird going on here. Let us know if you discover any more useful information.

**Comment by trotzig** [comment]
One thing that came to mind as I was reading this: Is there a chance the Waypoint is injected into the DOM before the content above? That's just speculation though. Any code you can post here would help track this down.

**Comment by zth** [comment]
Hey guys, and thanks a lot for your reply! I will get back to you with actual code ASAP, I'll try and get a fiddle set up. Talk to you soon again!

**Comment by ameensol** [comment]
Posting this here because I don't think it warrants opening a new issue, and is somewhat related to OP. 

I was, at first, having the same issue as the OP where the Waypoint `onEnter` was being triggered on every page load and then never firing again (and not firing `onLeave` either). This was happening because the Waypoint was placed at the end of a long (several times the window height) Feed component, and was always inside it. Specifically (and banally), the calculations in `_currentPosition` showed that the Waypoint was both above the bottom of and below the top of the Feed, which was true as soon as the page loaded. This confused me for a while, because I had assumed that the position of the Waypoint would be evaluated with respect to the window/viewport, and not just the whole encompassing parent component. I thought that it would work just like the demo fiddle, where the Waypoint `onEnter` is triggered as it becomes visible, and `onLeave` likewise triggered as it leaves the screen, with affordances made for `threshold`. However, when a long non-window parent component is used, the `onEnter` is calculating whether the Waypoint is indeed contained within that component, which is obviously true at all times unless ... that parent component has its *own* scrollbar and a fixed height. 

That wasn't clear to me from the outset, but I moved on.

I changed the Feed to be `overflow: hidden`, and now the `scrollableAncestor` is the `window`. This works. My only remaining confusion is that I want to trigger the `onEnter` something like 50% down the page, and since I'm using the window only, it seems weird that the threshold calculation uses the `innerHeight` property instead of the `document.body.offsetHeight`, because `innerHeight` is just the size of my screen, and `document.body.offsetHeight` is the height of the whole page, including the parts not shown. It does, however, make sense for the `isAboveBottom` and `isBelowTop` to use the `contextBottom` and `contextTop` values derived from `innerHeight` in determining the Waypoint's position, but when the `thresholdPx` is similarly derived from `innerHeight` it forces me to use values greater than 1 for the threshold to approximate the 50% down the page that I'm shooting for. This doesn't make sense to me, and I don't imagine it would make any sense to you all, so I'm pretty sure I'm doing something wrong here.  

In any case, I changed how the threshold is calculated when the scrollable parent is the window, and was able to get it working the way I know it was intended — I can now set the threshold to .5, and trigger the `onEnter` halfway down the page. 

Here's the (very slightly) altered code for the `_currentPosition` function: https://gist.github.com/2cf24017a7d43ab0c99c

Cheers, and thanks for the great component.

**Comment by trotzig** [comment]
Hi @ameensol and thanks for using react-waypoint! 

> This was happening because the Waypoint was placed at the end of a long (several times the window height) Feed component, and was always inside it.

The method to find the scrollable parent is somewhat limited, and we've tried explaining that in the [README](https://github.com/brigade/react-waypoint#limitations). More specifically, we only look at the calculated `overflow-y` or `overflow` property of a parent to determine its scrollable-ness. Would you mind sharing the CSS properties of the Feed? There might be something there that could highlight a bug with the current way we find the scrollable parent. Also, there's an [open PR](https://github.com/brigade/react-waypoint/pull/42) to allow you to pass in a custom scrollableParent, though I haven't seen any activity in the last week, so I'm not sure whether that person is actively working on it or not. That might help your usecase, but without more context I'm not sure. 

> My only remaining confusion is that I want to trigger the onEnter something like 50% down the page, and since I'm using the window only, it seems weird that the threshold calculation uses the innerHeight property instead of the document.body.offsetHeight

When we implemented the `threshold` support, we had [infinite scroll in mind](https://medium.com/brigade-engineering/to-infinity-and-beyond-with-react-waypoint-cb5ba46a9150#.yryy34p0a). When you do infinite scrolling, you don't want the trigger point to be based on the height of the container, because the container will grow for each "page" being injected at the bottom. 

However, I do realize that the supprt for `threshold` is somewhat limited, and I'd be open to creative PRs to extend how that can be used. For instance, I was in a situation last week where I needed a waypoint to trigger at exactly 56 pixels from the top. Using `threshold` here would have meant looking at the height of the window to compute it, which would feel brittle. 

Would you mind sharing a bit more about how you use the waypoint in the Feed? I think that could help figuring out what actions we could take to make your (and other developers) lives easier.

**Comment by ameensol** [comment]
I'm also doing an infinite scroll. I ended up implementing threshold like this: 
```js
    // .5 at page 0 bc halfway down page
    // .25 at page 1 bc 30/40 articles
    let threshold = 1 / (2 * (page + 1))
```
where page starts at 0 for the first set of articles in the feed, and is incremented after every article load. I realize now that my use case of loading at 50% down the page is a little convoluted, and it might be easier to trigger the waypoint say, when the user is 5x the height of their device away from the bottom or something along those lines, in which case the threshold would just be (5), or the multiple of device height from the end that I want waypoint triggered. I understand now why you guys have it as you do. I'm going to keep playing around with it and see if I like it my way or if I want to switch back. 

Thanks for the quick response and again for the awesome library!
