### ISSUE TITLE
Feature request: scrollTo

### ISSUE THREAD

**Issue by stereobooster** [brigade/react-waypoint#195]
Any chance you will add `scrollTo` functionality? Or there is more appropriate library for this?

**Comment by lencioni** [comment]
@stereobooster what would this functionality do?

**Comment by jmeas** [comment]
Hi @stereobooster ! I use [react-scroll](https://github.com/fisshy/react-scroll) in conjunction with Waypoint sometimes. I can definitely see how they could be merged into the same library, but I kinda like them being separate. They both do one thing really well.

@lencioni , I use it for a scrollspy navigation. Consider a nav bar to the left, and content to the right.

When a user clicks a navigation item, they are scrolled to a section of the page. Each section of the page has an associated Waypoint, which in turn causes the corresponding nav item to be highlighted. Because the Waypoints and "scroll links" map one-to-one in this situation, one might think that it could just be one library.

@stereobooster , are you setting up a similar thing?

**Comment by lencioni** [comment]
@jmeas couldn't you use regular inline links for that?

**Comment by stereobooster** [comment]
Scroll to exact element. I have list of items on left and map on the right. I want to scroll to corresponding item in a list when I click marker. I able to center marker on the when I scroll list

**Comment by stereobooster** [comment]
> @jmeas couldn't you use regular inline links for that?

Well anchors can conflict with react-router (in theory haven't tried that).

@jmeas so react-scroll. I will give a try. 

>  I can definitely see how they could be merged into the same library, but I kinda like them being separate. They both do one thing really well.

Can we have one library, but clearly separated components? 

I wanted to use [react-lazy-load](https://github.com/loktar00/react-lazy-load/), but realized it is much easier to write my own component based on waypoint, which supports lqip, lazy-load, and responsive. This is because waypoint is good "primitive", so it easy to construct "lightweight" components based on it.

**Comment by jmeas** [comment]
> @jmeas couldn't you use regular inline links for that?

Yup, this does works for some projects. The only downside is that there's not much of an API when it comes to regular inline links. For instance, with regular inline links, the user is teleported instantly, rather than smoothly scrolled. We needed an animated scroll for the experience in this particular app, so we're using `react-scroll`.

---

Another option, which I just found through google, is [native scrolling](https://css-tricks.com/snippets/jquery/smooth-scrolling/). You could use this (or its polyfill) + refs to implement this without any library (although you may want some system to manage your refs).

> Can we have one library, but clearly separated components?

I'm not convinced we really get anything out of making them the same lib. Right now there are clearly separated components, managed by two different teams. This seems like a good system to me, because they're working on making the best scroll component, and we're working on making the best waypoint component. What do you think, @stereobooster ?

**Comment by lencioni** [comment]
Yep, if you need smooth scrolling, I'd go with `Element.scrollIntoView()` and a polyfill. I know some folks at Airbnb have set that up and I haven't heard of any issues with it.

https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

airbnb-browser-shims brings in smoothscroll-polyfill

- https://www.npmjs.com/package/airbnb-browser-shims
- https://www.npmjs.com/package/smoothscroll-polyfill

> I'm not convinced we really get anything out of making them the same lib. Right now there are clearly separated components, managed by two different teams. This seems like a good system to me, because they're working on making the best scroll component, and we're working on making the best waypoint component.

👍

**Comment by stereobooster** [comment]
Huh, this is something new. Haven't seen `Element.scrollIntoView()`.

> I'm not convinced we really get anything out of making them the same lib

Well they share some functionality - measuring position of elements.

But I have no strong preference. Will try suggested solutions. Thanks a lot
