### ISSUE TITLE
Mixin needed

### ISSUE THREAD

**Issue by edygar** [brigade/react-waypoint#2]
The component itself doesn't need to render anything, just a DOM Node to listen to.

It would be nice if the waypoint behavior was extracted and provided by a Mixin along with the Component.

**Comment by trotzig** [comment]
We have explored that solution too, but having the triggering behavior attached to a dimension-less element actually simplifies a few things. Do you have a particular use-case in mind? I can think of one where you want to know when an entire element is in view.

**Comment by edygar** [comment]
I've seen the ways around to my problem, but thought that would be a good case for a mixin.

The case in particular is this [site's behavior](http://www.mfiusa.com.br/): when you scroll you will notice that it affects both the window.location.hash and menu nav (while this site wasn't done with ReactJS, I was considering rewriting using it.).

**Comment by trotzig** [comment]
I see, thanks for providing that link! 

I think you could solve that through a component that wraps content in between two Waypoints.  We have also been discussing passing along a `edge` or `direction` param with the `onEnter` and `onLeave` events so that you know at what edge of the scrollable container the Waypoint is triggered. 

I just had a conversation with @graue about this issue, so there might be a more common use-case than I thought. 

Taking the height of a box into account when deciding when to trigger has been a common source of performance issues for me in the past. I'm slightly worried that performance will get worse when we do that. There are definitely ways to mitigate that, and it might not be hard at all. 

We're definitely open to a PR if you or someone else wants to tackle this use-case!

**Comment by edygar** [comment]
Now thinking, the mixin idea is for a completely different scenario, which emerges a different proposal.

Somehow I would expect an state to be set, no callbacks to be triggered, so I could render the component accordingly with the new state.  And as you mentioned, it would add bidimensional complexity and it probably would need handle horizontal scrolls.

I think it is way more complex, and deserves a careful look other than just extract the behavior from the react-waypoing, which already solves the vertical scrolls elegantly, and that's enough for it.
