### ISSUE TITLE
Inverting / Overlapping Boundaries / Offsets

### ISSUE THREAD

**Issue by iDVB** [brigade/react-waypoint#211]
I "think" I know what I'm asking about.
I'd like to have the **topOffset** be lower then the **bottomOffset** so they overlap.

The exacted behaviour is that the item will **ENTER** at the vertical center of the window. It will also **LEAVE** lower then that, at approx the bottom 1/4 of the window.

I think because I'm entering values like this, waypoint is choking something, maybe because usually those offsets do not overlap.?

![Example](https://goo.gl/qkkLHN)

**Comment by jmeas** [comment]
> I "think" I know what I'm asking about.

😂

I get what you're asking, and I haven't done this myself. Have you considered just switching them, so that you use the bottom boundary for the top, and the top boundary for the bottom?

> maybe because usually those offsets do not overlap.?

This is how I use them, although we should probably allow for them to overlap.

> The exacted behaviour is that the item will ENTER at the vertical center of the window. It will also LEAVE lower then that, at approx the bottom 1/4 of the window.

This is useful. Can you also provide us with:

1. the props that you're passing
2. the behavior that you're seeing

Sorry for the issues you're running into, @iDVB !

**Comment by jmeas** [comment]
@iDVB , just checking in...did you ever figure this out? After the above post, I did a quick read of the code, and nothing immediately stood out to me as something that wouldn't support inverted boundaries. But it's possible that I missed something.

**Comment by iDVB** [comment]
I think you are right, after I posted, I realized that how we were using them was not exactly as I thought/posted. In the end we ended up simplifying the code by writing something a bit custom.

Thanks for helping to noodle this one though!

**Comment by jmeas** [comment]
Cool, cool. Glad you figured it out! 👌
