### ISSUE TITLE
wrong value for currentPosition

### ISSUE THREAD

**Issue by yenly** [brigade/react-waypoint#214]
For context, I have a react component with a long article page. I added Waypoint to a containing div at the bottom called stitchedContent with the position of relative to stitch in more articles. In initial load, my div is out of viewport but the onEnter fires with currentPostion: 'inside' 

I turned on debug and scrolled up and down to see the changes values. I don't see currentPosition set to outside. Is this a bug? 

I also tried wrapping my child component with Waypoint but when it scrolls into view, it doesn't trigger onEnter.

**Comment by trotzig** [comment]
In most cases where I've seen this behavior, it's been because there's something being lazy-loaded on the page above the waypoint. One such thing could be `<img>` tags without a set height. Another could be some css being applied after the initial render. Could you share a little bit more about your setup?

**Comment by yenly** [comment]
Thanks for the quick response! My react component is pretty complicated using react-async-script to load third party js files for article content. I do have <img> tags without set height since these article images are entered by authors and editors and I have no control over them. Is there any work around?

**Comment by jmeas** [comment]
Hi @yenly ! Sorry that you're running into this problem. What you're describing sounds like it could be the same cause as these other issues ( #43, #47, #83, https://github.com/brigade/react-waypoint/issues/133#issuecomment-258762555 ).

The tl;dr is that during the first few milliseconds of your application load, elements on the page might be in a different location than they are once the app is loaded. This is because CSS is still being applied, the React app is being bootstrapped, so new elements are being added dynamically, images are loading and pushing other elements down, and so on. This can cause Waypoints that will eventually appear at the bottom of the page to be rendered at the top of the page for a fraction of a second.

This can happen so fast that it might be hard to notice, but it will still trigger the `onEnter` callback if the Waypoint ever renders within the viewport during this loading phase.

There are a few proposed solutions in those issues. Give those a read, and let us know if this sounds like describes your problem.

If, after reading those issues, you're able to solve things, then great! If not, just leave us another comment in this thread and we can try and help you out more.

Good luck!

**Comment by yenly** [comment]
I got it working by setting  scrollableAncestor={window}! :)
```
<Waypoint
  key={i}
  topOffset={'75%'}
  bottomOffset={'-5%'}
  scrollableAncestor={window}
  onEnter={this.handleOnEnter}
  onLeave={this.handleOnLeave}>
  <Article key={i} post={item} postContent={parseContent} />
</Waypoint>
```
When each child component enters/leave the viewpoint, I want to trigger specific events pertaining to that child component. How do I assess the Waypoint key in my handleOnEnter or handleOnLeave functions? 

I read in your docs, "You can then use a key prop to control when a waypoint is reused vs. re-created." I'm not sure I understand how to use this. Do you have examples I can look at to understand how to use it?

Thanks in advance for all your help!

**Comment by jmeas** [comment]
> I got it working by setting scrollableAncestor={window}! :)

Awesome! I'm glad you figured that out!

> How do I assess the Waypoint key in my handleOnEnter or handleOnLeave functions?

I usually do something like this:

```js
onEnter={() => this.handleOnEnter(i)}
```

**Comment by trotzig** [comment]
> I read in your docs, "You can then use a key prop to control when a waypoint is reused vs. re-created." I'm not sure I understand how to use this. Do you have examples I can look at to understand how to use it?

I agree this is tricky. One way we use this in our app is on infinite scrolling. Something like 

```jsx
<div>
  {this.state.items.map((item) => this.renderItem);
  {this.state.hasMoreItems && 
    <Waypoint key={this.state.cursor} onEnter={this.loadMoreItems} />
  }
</div>
```

This isn't strictly necessary but it fixes an issue with using waypoints on tall screens, where a batch of items doesn't fill the entire height of the screen. If we hadn't used the key, the waypoint wouldn't trigger a `this.loadMoreItems` (since it was never pushed off-screen). By using a `key`, we make sure that it triggers anyway (using the fact that waypoints trigger on mount).

**Comment by yenly** [comment]
I'm encountering duplicate keys errors even though in my logic, I use `i++` to increment the value as I push each Waypoint component to my articlesArray. This happens after I first scroll down and then scroll back up. Am I using the key wrong?
```
<Waypoint
  key={i}
  topOffset={'75%'}
  bottomOffset={'-5%'}
  scrollableAncestor={window}
  onEnter={({ previousPosition, currentPosition }) => {
    if (previousPosition === 'below' && currentPosition === 'inside') {
      this.displayNextArticle(i)
    }
  }}>
  <Article post={item} postContent={parseContent} />
</Waypoint>```

```
Warning: flattenChildren(...): Encountered two children with the same key, `1`. Child keys must be unique; when two children share a key, only the first child will be used.
    in div (created by PostView)
    in PostView (created by AsyncScriptLoader(PostView))
    in AsyncScriptLoader(PostView) (created by Connect(AsyncScriptLoader(PostView)))
    in Connect(AsyncScriptLoader(PostView)) (created by RouterContext)
    in div (created by SiteLayout)
    in SiteLayout (created by PageTransition)
    in div (created by PageTransition)
    in PageTransition (created by CoreLayout)
    in div (created by CoreLayout)
    in CoreLayout (created by RouterContext)
    in RouterContext (created by Router)
    in ScrollBehaviorContext (created by Router)
    in Router (created by App)
    in div (created by App)
    in Provider (created by App)
    in App```

**Comment by jmeas** [comment]
@yenly could you paste more of your code? Perhaps the whole JSX block of the render?

**Comment by yenly** [comment]
Would this help?
```
loadInitialArticle = () => {
    const { post } = this.props
    if (post) {
      post.content = parseShortcodesInString(post.content)
      const loadInitialArticle = <Waypoint
        key={0}
        topOffset={'75%'}
        bottomOffset={'-5%'}
        scrollableAncestor={window}
        onEnter={() => {
          this.displayNextArticle(0)
        }}
        fireOnRapidScroll>
        <Article post={post} postContent={post.content} />
      </Waypoint>
      this.setState({ articlesCollection: [loadInitialArticle] })
    }
  }

  loadArticleCollection = () => {
    const { chartbeatPosts } = this.props
    if (chartbeatPosts.items && !chartbeatPosts.isLoading) {
      const articlesToLoadArray = chartbeatPosts.items.map((item, i) => {
        const parseContent = parseShortcodesInString(item.content)
        i++
        return (
          <Waypoint
            key={item.id}
            topOffset={'75%'}
            bottomOffset={'-5%'}
            scrollableAncestor={window}
            onEnter={({ previousPosition, currentPosition }) => {
              if (previousPosition === 'below' && currentPosition === 'inside') {
                this.displayNextArticle(i)
              }
            }}>
            <Article post={item} postContent={parseContent} />
          </Waypoint>
        )
      })
      this.setState({ articlesToDisplay: articlesToLoadArray })
    }
  }

  displayNextArticle = (articleIndex) => {
    let tempArray = this.state.articlesCollection
    tempArray.push(this.state.articlesToDisplay[articleIndex])
    this.setState({ articlesCollection: tempArray })
  }

  render () {
    const { post } = this.props

    let articleArray = []
    if (!post || post.isLoading) {
      return <div className='container'><h1>Loading Post...</h1></div>
    }

    if (post.fetchFailed) {
      return <div className='container'><h1>Failed to find post.</h1></div>
    }

    // console.log('articles to display', this.state.articlesToDisplay)
    articleArray = this.state.articlesCollection

    return (
      <div className={styles.postView}>
        {articleArray}
      </div>
    )
  }
```

**Comment by yenly** [comment]
I solved it by keeping track a list of unique ids and checking item.id against it before adding to articlesToDisplay. Thanks for all your help!

**Comment by jmeas** [comment]
Awesome! 👌 

I'm glad you were able to figure it out, @yenly 🙂
