### ISSUE TITLE
Error after updated to v7.3.0

### ISSUE THREAD

**Issue by colloquet** [brigade/react-waypoint#221]
Hi,

I have updated react-waypoint to 7.3.0 today and I am getting this error:

<img width="1046" alt="screen shot 2017-10-04 at 11 51 59 am" src="https://user-images.githubusercontent.com/6201495/31159302-97adaf1a-a8fa-11e7-8b1e-24f1afe4a18d.png">

Everything is working fine after I revert back to v7.2.0

Is this a bug or am I missing something?

Thanks!

**Comment by trotzig** [comment]
The mjs extension was added (and discussed) in https://github.com/brigade/react-waypoint/pull/220. I don't have much context on that change, so I'm going to ask @lencioni for help here. Thanks for taking the time to report this.

**Comment by lencioni** [comment]
Hi, sorry you are running into this issue!

It's a little hard for me to understand what might be going wrong from just
looking at your screenshot. Is there any chance you could put up a repo
that minimally reproduces the issue?

**Comment by colloquet** [comment]
Hi @lencioni ,

I have quickly setup a react app using create-react-app:

[https://github.com/colloquet/waypoint-test](https://github.com/colloquet/waypoint-test)

I have only added react-waypoint v7.3.0 and a Waypoint component to App.js and still getting the same error.

Colloque

**Comment by dominikbulaj** [comment]
I have exactly the same problem after upgrading to 7.3.0 
When I force version 7.2.0 it works. Same issue as in @colloquet case.

**Comment by waterizzet** [comment]
Unfortunately I've run into the same problem. After updating it to 7.3 it started giving me a similar error:

invariant.js:42 Uncaught Error: Invalid tag: /static/media/index.73a4b08a.mjs
    at invariant (invariant.js:42)
    at validateDangerousTag (ReactDOMComponent.js:343)
    at new ReactDOMComponent (ReactDOMComponent.js:370)
    at Object.createInternalComponent (ReactHostComponent.js:39)
    at instantiateReactComponent (instantiateReactComponent.js:77)
    ...

**Comment by lencioni** [comment]
Thanks for the repo, it was very helpful.

I'm not super familiar with create-react-app, but it seems to me that its webpack has been configured to recognize files with names that end in `.mjs` as a static asset, so instead of returning a reference to what is being exported, it is outputing the file in static/media and giving you a string with the path to this file.

I opened an issue on create-react-app here: https://github.com/facebookincubator/create-react-app/issues/3237

In the short term, you can either stick with 7.2.0 for now, or import waypoint like `import Waypoint from 'react-waypoint/build/index.js';`

Sorry for the trouble, I hope we can get this resolved soon!

**Comment by jnsdls** [comment]
same issue here, glad you reported it upstream to CRA, will track both that and this and stick with 7.2.0 for now :)

**Comment by trotzig** [comment]
A fix for this was released in 7.3.1. Thanks for the quick reports everyone!

**Comment by colloquet** [comment]
Thanks! Appreciate your help!

**Comment by benbrandt** [comment]
What is the motivation for going with `.mjs`? Most libraries that have `/es/` imports still use `.js`. It just requires a lot of changes in the build process (webpack/eslint/flow) to support an additional file extension, that from my understanding, is a new extension for node?
Just curious to get some insight on the decision. Thanks!

**Comment by jmeas** [comment]
> that from my understanding, is a new extension for node?

This is exactly right, and is the primary reason for the decision. Although it's still early on, there's a good chance that `.mjs` will one day be the extension that is typically associated with the usage of ES2015 modules.

This library has just adopted this pattern a bit early.

> It just requires a lot of changes in the build process (webpack/eslint/jest/flow) to support an additional file extension

I brought up these concerns when we merged in the PR that added this extension. So far, the team has decided that it's worth any issues we might run into. My favorite part of the folks who work on Waypoint is that they're really reasonable. If the extension ends up causing too many issues for users, then I'm sure the team would consider switching back to `.js`, even if only for a period of time. For now, though, 7.3.1 seems stable. Have you run into specific issues with other tooling on the latest release?

**Comment by benbrandt** [comment]
I tried updating all of the places I could think of with the new extension and kept getting errors, so I gave up and stuck with cjs for now. I'll keep watching the repo to see what happens here and try again later

**Comment by jmeas** [comment]
> I tried updating all of the places I could think of with the new extension and kept getting errors, so I gave up and stuck with cjs for now.

Ah, alright. I'm sorry you're running into those issues, @benbrandt . If you post more details about what sorts of errors you were seeing with the `.mjs` extension, someone may be able to help out. Also, I'd be curious to know what happens if you manually go into `node_modules` and change both the `package.json` and source files to have a `.js` extension. There's a chance that your tooling is blowing up due to the ES modules syntax, rather than the file extension.
