### ISSUE TITLE
Module build failed: Error: Couldn't find preset "airbnb" relative to directory

### ISSUE THREAD

**Issue by davidlampon** [brigade/react-waypoint#240]
This happens for me on 8.0.0 but not on 7.3.4. I haven't gone deeper into the issue, just wanted to report it.

**Comment by trotzig** [comment]
The airbnb preset is a dev dependency. Is it possible your webpack/rollup setup is picking up the local .babelrc and trying to compile the source directly?

**Comment by hiredgun** [comment]
It seems like webpack's babel-loader section doesn't properly exclude node_modules directory. @davidlampon check that you don't have some typo in exclude property in your webpack config. If not, then make sure you're using regex literal as exclude value instead of a string. Is should look like this:

```js
 {
     test: /\.jsx?$/,
     loader: 'babel-loader',
     exclude: /node_modules/,  // <--- regex literal
}
```

**Comment by MatthewHerbst** [comment]
@davidlampon did you solve your issue?

**Comment by davidlampon** [comment]
Sure, thanks!

**Comment by arizonatribe** [comment]
I was getting this same error too, however I was already using an `exclude` path with a negative look-ahead to handle our company's internal NPM packages:
```
exclude: /node_modules\/(?!@our-company\/).*/
```

That worked fine on Mac/Linux but failed for Windows users because the path-separator is different. 

Following the tip in [this stackoverflow thread](https://stackoverflow.com/questions/38189757/regex-in-webpack-loader-exclude-include-config-doesnt-work?rq=1) changed it to this and it worked:
```
const EXCLUDE_PATTERN = new RegExp(`node_modules\\${path.sep}(?!@our-company\\${path.sep}).*`);
...
exclude: EXCLUDE_PATTERN
```
