### ISSUE TITLE
currentPosition: above and below is reversed. XDDDD

### ISSUE THREAD

**Issue by rockmandash** [brigade/react-waypoint#242]
currentPosition: above and below is reversed. XDDDD

**Comment by jmeas** [comment]
Hmmm, I'm not too sure what you mean. Can you provide more details here?

**Comment by rockmandash** [comment]
![image](https://user-images.githubusercontent.com/7580792/35789332-77da3446-0a76-11e8-93b7-1de6ee37960d.png)
Here currentPosition is below, actully is above XDDD

**Comment by jmeas** [comment]
@rockmandash , it is difficult to debug the problem with the information you've given. Is this project open source? Could you make an isolated example where we can take a look?

Because of the way the DOM loads, sometimes the initial render of a waypoint can be where you may not expect it to be. Throttling the network in DevTools to a very slow speed (like Slow 3G) can sometimes make these "oddities" make more sense.

**Comment by rockmandash** [comment]
Thank you for your reply >////<

**Comment by jmeas** [comment]
Were you able to figure it out? 😮 ❓

**Comment by rockmandash** [comment]
As long as the code works lol.........

**Comment by trotzig** [comment]
@rockmandash I'm glad it's working, but if this is a bug it would be very helpful if you could provide more details!

**Comment by rockmandash** [comment]
I have make this pen
[![Edit lyqlj2rlz7](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lyqlj2rlz7)
Please check it out, the current position is reversed.

**Comment by rockmandash** [comment]
Oh no, I think what you mean in the code!
The currentPosition is relative to user's view!!!!!!!!!!!!
No wonder I think it is reversed.
