### ISSUE TITLE
onEnter / onLeave not re-fired after component updates

### ISSUE THREAD

**Issue by kenaniah** [brigade/react-waypoint#49]
This becomes an issue if the waypoint ends up with the same position after a component update. Use case is that the component was triggered initially with a position of `inside`, called onEnter (which then loaded more elements, causing a component update), and then ended up with a position of `inside` again. In the case of a single waypoint, onEnter / onLeave would not be fired again (as the position was not changed)

**Comment by kenaniah** [comment]
FYI, this may be fixed by adding `this._previousPosition = null` to the `componentDidUpdate()` function.

**Comment by trotzig** [comment]
I see your issue, and why re-triggering onEnter would solve that. But constantly firing onEnter on component update would quickly become a problem I think. One way you can solve the issue you are describing is to set a `key` prop on the waypoint that changes when a new "page" has been loaded. This will cause a new waypoint to be mounted instead of updating a previous one.

```jsx
<Waypoint key={index} onEnter={...} />
```

**Comment by kenaniah** [comment]
@trotzig - I just verified that setting the `key` prop works perfectly for my use case. Thanks for the tip. It would be great to see an example of this use case somewhere in the docs ;-)

**Comment by trotzig** [comment]
Great! I added some info to the readme in the "Usage" section: 
https://github.com/brigade/react-waypoint#usage

Let me know if you think that's enough!

**Comment by kenaniah** [comment]
Perfect. Thanks for the quick turnaround!
