### ISSUE TITLE
Browser-ready file?

### ISSUE THREAD

**Issue by rmosolgo** [brigade/react-waypoint#62]
Hi, looks like a great library!

I'm hoping to try it out but I'm looking for a browser-ready file, something I could just put in `<script src="...">`. Does this library have one of those? I looked for a `/dist`, or a CDN, but I didn't see anything. 

The closest I found was http://brigade.github.io/react-waypoint/src/waypoint.js, but it doesn't look like _exactly_ the output of https://github.com/brigade/react-waypoint/blob/master/src/waypoint.jsx (maybe an older version though?).

Thanks!  Sorry for asking a question from 2012 :laughing:

**Comment by trotzig** [comment]
I'm glad someone is asking 2012 questions. :)

At the moment there is no browser-ready build. The one you linked to is an old version that (if I remember correctly) I hand-made for the demo page. From the top of my head, I don't know how to make the es6 module browser-ready. Though I think it will involve something like this:
1. Transpile to an es5 module using babel (this is what we do when we publish the npm package)
2. Transform that es5 module to a standalone browser-ready script. 

For 1, you can look in `package.json` for the `build-npm` script we use (invoked using `npm run build-npm`):
```json
  "scripts": {
    "build-npm": "rm -rf build/npm && mkdir -p build/npm && babel src/waypoint.jsx --out-file build/npm/waypoint.js",
    "test": "./node_modules/.bin/eslint . --ext .js,.jsx && ./node_modules/.bin/karma start",
    "prepublish": "npm run build-npm"
  },
```

For 2, this resource might help:
http://stackoverflow.com/questions/7576001/how-to-require-commonjs-modules-in-the-browser
I only skimmed that page, so I don't know if it has enough information. 

When we know how to do step 2, we can add it as a new script to `package.json`, e.g. 
```json
  "scripts": {
    "build-npm": "rm -rf build/npm && mkdir -p build/npm && babel src/waypoint.jsx --out-file build/npm/waypoint.js",
    "build-browser-standalone": "npm run build-npm && browser-transform build/npm/waypoint.js --out-file waypoint-browser-ready.js",
    "test": "./node_modules/.bin/eslint . --ext .js,.jsx && ./node_modules/.bin/karma start",
    "prepublish": "npm run build-npm"
  },
```
Since you have most context on how you plan to use the script, it would be great if you could do some exploration! I'd be happy to accept a PR for this.

**Comment by rmosolgo** [comment]
Thanks for the suggestions, we ended up taking another approach but if we come back to waypoints, I'll give it a try!
