### ISSUE TITLE
Not working with Semantic UI

### ISSUE THREAD

**Issue by FunProject** [brigade/react-waypoint#63]
Hello,
I was using react-waypoint with Twitter Bootstrap 3 => everything was working. Now I am migrating to the [Semantic UI](http://semantic-ui.com/). Everything is working except the react-waypoint. It does not trigger onEnter action. If I does not include Semantic UI CSS file, react-waypoint works again.

**Comment by lencioni** [comment]
Hi @FunProject! Will you please put together a repo with a simple repro case so we can help you debug?

**Comment by FunProject** [comment]
Hello,
[I have created sample repo.](https://github.com/FunProject/react-waypoint-semantic) Hope you can help me. Thank you.

**Comment by trotzig** [comment]
That's quite a big repro case, any chance you can slim it down? 

One possible theory (without actually finding any support for it) is that Semantic UI has an `overflow: auto|scroll` somewhere which is causing the waypoint to use the "wrong" scrollable ancestor. You can try that theory by either inspecting the waypoint to see what its `this.scrollableAncestor` is. If it's not pointing at the right element (should be `window` in your case I think), that's probably where the problem is. You can manually override the `scrollableAncestor` through a prop passed to waypoint, e.g. `<Waypoint scrollableAncestor={window}/>`, though I would encourage you to dig deeper even if this helps you. You might be able to help others using Semantic UI as well.

**Comment by FunProject** [comment]
Yes! You are right.
I checked event listeners and I have realized that in Bootstrap the scrollableAncestor is referencing to "Window":
![bootstrap](https://cloud.githubusercontent.com/assets/3946448/13743698/a01953f2-e9e3-11e5-982c-b2a6207525b8.png)

but if I use Semantic UI CSS, it's referencing to "body" element.
![semantic](https://cloud.githubusercontent.com/assets/3946448/13743697/a0163424-e9e3-11e5-9d2b-05a2b7450564.png)

Please can you help me? I'm not experienced enough to solve this problem by myself. 
Thank You!

**Comment by FunProject** [comment]
Ok, so update,
I have just added scrollableAncestor={window} to the Waypoint component (as @trotzig mentioned :-)) and everything is working now!

**Comment by trotzig** [comment]
I'm glad you got things resolved. There might be a bug somewhere here (https://github.com/brigade/react-waypoint/pull/57 is related), but I'm not sure what it is. Do you happen to know where that id and class names come from? I'm thinking of `#syno-nsc-ext-gen3.ext-webkit.ext-chrome.ext-max`. To me it looks like a chrome extension, I doubt that it's something that Semantic UI is adding. It's definitely not added by the Semantic UI CSS, since that wouldn't manipulate the DOM (adding classes/id).
