### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by lord-xeon** [brigade/react-waypoint#66]
Would it be possible to enable waypoints on horizontal scrolling nodes?

I have a vertical list of items that I want to load more of while scrolling, but on smaller screens it switches to a horizontal scrolling implementation.  However, the waypoint loads everything initially.

**Comment by trotzig** [comment]
Possible yes, but we'd have to add that functionality. I've anticipated this to come up, and I'm actually surprised no one asked for it until now. 

There are two paths we can take when implementing this:
A) Support horizontal and vertical scrolling at the same time.
B) Add a `direction` prop (or similar) that tells the waypoint what scroll direction we're anticipating.

A is more "correct", but likely harder to implement and will probably come with some performance penalties. 

B is less flexible (you have to know upfront what scroll direction is being used), but likely easier to implement in a performant way.

We'd be happy to accept a PR for this!

**Comment by Echooff3** [comment]
Can you explain in more detail how to implement option B? I've got a similar scrolling setup. Thanks!

**Comment by trotzig** [comment]
I haven't thought too much about this, but from a surface level, I think this is roughly what you'd have to do:

In `_findScrollableAncestor`, check for `overflow-x` instead of `overflow-y` if the `direction` prop is `'horizontal'`. 

Add `POSITIONS.left` and `POSITIONS.right`. Change `_currentPosition` so that it returns these new positions for horizontal waypoints. We might have to fork `_currentPosition` based on the `direction` prop, I'm not sure.

In ` _handleScroll`, fire `onEnter` and `onLeave` based on the new left and right positions.

**Comment by jmeas** [comment]
If anyone wants to tackle this, and wants to pair or brainstorm some ideas, just lmk. I'd be happy to help.

(I don't need it personally, but I think it's a good feature to add and might not add much code)

**Comment by jmeas** [comment]
Closing as this was implemented in #137 and released as [4.1.0](https://github.com/brigade/react-waypoint/releases/tag/v4.1.0)
