### ISSUE TITLE
Limiting scroll callback frequency

### ISSUE THREAD

**Issue by jmeas** [brigade/react-waypoint#73]
Have you considered limiting the frequency with which `_handleScroll` is called via requestAnimationFrame + throttling?

**Comment by trotzig** [comment]
Are you experiencing performance issues? I'd like to understand those first before we go down a throttling/delay path. 

When we first started writing this component, we actually assumed that we would have to throttle in some way. But it turned out to work just fine without it. There are some cases though where the positioning calculation can get expensive. I think the further out the DOM tree you are, the more expensive it gets. The cheapest waypoints are (most likely) those that are direct children of <body>. 

I've been wanting to find a good way to quantify performance however. If you can think of ways to add a benchmark script of some sort, I'd be happy for some feedback!

**Comment by jmeas** [comment]
I've worked on apps where throttling the scroll handler has impacted performance, though I'm not encountering perf issues with this lib atm. Actually, I'm not even using it yet (though I do plan to add it into my app in the next week). I was just browsing the source to see how it worked under the hood.

My prediction is that on slower machines (like phones), the upper limit of waypoints could be limited by this lack of throttling.

The case that I'm using it for will have only have a few waypoints, so I don't think this will cause perf problems on the machines that I'm targeting.

I've added it to my todo list to explore this further. I'll get back to you – but it might be some time! Feel free to close the issue in the meantime ;)

**Comment by trotzig** [comment]
Thanks for the details. I'm glad you're using our library. :)

I've seen performance issues related to waypoints in some cases. Those have usually not been because of waypoint triggering, but because the result of an `onEnter`/`onLeave` call is updating the UI in some way. 

There's definitely a limit to how many waypoints you can use on a page, and that number is going to be smaller on mobile. It would be great to quantify this in some way, I'm interested in finding out the performance footprint waypoints have. It would be great if you could dive into that at some point!

**Comment by jmeas** [comment]
Update for future readers: #98 added this, and it was released in [v3.0.0](https://github.com/brigade/react-waypoint/releases/tag/v3.0.0).

**Comment by babruix** [comment]
Just to note, so no one is confused, throttleHandler was removed in https://github.com/civiccc/react-waypoint/blob/master/CHANGELOG.md#500

**Comment by Nantris** [comment]
It seems like for us the cause of the lag is certainly react-waypoint itself. Is there anything that could be done incorrectly on our end that might cause this issue? We're seeing execution times like below (~175ms) per item, and a list potentially has dozens of items.

![image](https://user-images.githubusercontent.com/6835891/184725927-22e5a370-9eba-4636-b415-c842e630f4a6.png)

**Comment by lencioni** [comment]
I'd recommend switching to IntersectionObserver (possibly via react-intersection-observer)

**Comment by Nantris** [comment]
Thanks for the tip @lencioni! I assume that `getBounds` is the bottleneck on performance and using IntersectionObserver avoids that? Is there a reason react-waypoint doesn't or can't use it behind the scenes?

**Comment by lencioni** [comment]
See #197 but also just using IntersectionObserver directly or via react-intersection-observer will be a better choice.
