### ISSUE TITLE
How about to add TopOffset and BottomOffset options for this tool?

### ISSUE THREAD

**Issue by bibobibo** [brigade/react-waypoint#77]
We have some sticky element in the scroll container, the sticky element height is const. In our case, the topLine is not really the scroll container top. so we need to add the topOffset and bottomOffset for the scroll container. Do you think it is necessary to add these two options for react-waypoint or make the threshold more flexible?

**Comment by trotzig** [comment]
If I understand your issue correctly, you have something like this:

```
 -- scrollable container-----
|-- sticky bar --------------|
|--- waypoint ---------------|
|                            |
|                            |
|                            |
|                            |
|                            |
 ----------------------------
```

And you want to trigger the waypoint when it hits the sticky bar. Is that correct? 

I've actually had the same issue myself. I think I solved it at that time by hacking together something where the waypoint was inside a container with negative top position. That wasn't a great solution. I wonder if we could fix this by allowing the `threshold` prop to be a string as well? Then we could do something like 

```jsx
const STICKY_BAR_HEIGHT = '50px';
<Waypoint onEnter={handleEnter) threshold={STICKY_BAR_HEIGHT} />
```

I think that should be fairly easy to implement. Are you willing to take this on and write a PR?

**Comment by lencioni** [comment]
I think the threshold should behave more like CSS values, and if it is a number, it is treated as px. This would allow us to use `threshold={100}` to mean 100px, and `threshold='100px'`/`threshold='100%'` are a lot more intuitive.

**Comment by trotzig** [comment]
That sounds like a good idea @lencioni. 

Would `20%` be the same as `0.2` (as we have today)?

If we decide to implement support for these units, I suggest we continue to support the current setup, but log a deprecation warning if you do. So `threshold={0.2}` would be translated to `20%` and generate a warning of the following kind:

```
Support for floating point threshold is going away soon. Please use `'20%'` instead of `0.2`. 
```

It gets a little tricky if you use `threshold={1}` however. Hmm, maybe we should just rename the prop and throw an error instead? I guess proper release notes could work too, but in my experience people don't read them too carefully, and a change to the behavior of a prop can have bad consequences.

**Comment by lencioni** [comment]
Yes `0.2` would become `'20%'`. I think pairing this with a major version change and a codemod that will fix the problems for you should be good.

**Comment by jmeas** [comment]
Is updating the `threshold` property enough to support the use case presented? My use case is like the ones described above: a fixed header. However, I don't think it's as simple as updating the `threshold` value to support pixels, though. Atm it looks to me as if the threshold affects both the top and bottom edges of the container. For a fixed header, it should only affect the top, right?

**Comment by jmeas** [comment]
I forked this project to implement this feature, and it's given me a new perspective on the issue. I think of threshold and offsets as ultimately changing the same value used in the algorithm (the position of the boundary used to determine whether the element is in view or not), but it's more expressive to keep the values separate, considering how they're likely to be used.

`threshold` pushes the boundary _out_ from the edge of the container. A threshold of 0 means that the boundary is right at the edge of the container. A threshold of 1 means that the boundary has been pushed out to a distance equal to the height of the element. Also, it's most likely that folks will want to use a percentage of the threshold to make sure that elements are at least halfway past the boundary before they're considered visible.

The offset described for the menu is different for two reasons. The first is that it requires the boundary to be pushed _in_. Another consideration is that it's likely to be expressed in pixels given its purpose.

Accomplishing just one of these with a single prop is not a problem (although I think `threshold="-100px"` isn't the most expressive API in the world for specifying a header that is 100px tall).

When consumers want to use both at once, though, things can get messy.

To illustrate that point, consider two elements. We want the following behavior:

1. account for a 50px header
2. only consider them visible when they're 50% past the header

If one of the elements has a height of 200px and the other 350px, what what would you need to use as the value to achieve the same effect? The answer is `threshold="-50px"` for the 200px tall one and `threshold="-100px"` for the 350px tall one.

...Actually, it's `"-125px"` for the 350px tall one. Oh, and the values are supposed to be positive values, not negative. I think it's tough for a person to identify those (pretty big) errors with this sort of API because of its lack of expressiveness.

Instead, I think the most flexible and expressive API (though certainly not the smallest!) would be to provide two threshold and two offset values: one for the top, one for the bottom.

Configuring this lib to solve the above problem with this API would then be the same for both elements:

```jsx
<Waypoint offsetTop="50px" thresholdTop={0.5} />`
```

This seems way more expressive to me. What do y'all think?

**Comment by trotzig** [comment]
Thanks for taking the time to dig deeper into this @jmeas. I agree that `threshold` doesn't feel like the right name for the usecase of taking a fixed navbar (or something) into account. Though I'm not sold on the split props. I understand why you're suggesting it, but I had to read the text a few times to understand the difference. I worry that people aren't going to use the right prop. 

You're definitely right about us needing two different offsets - one for bottom and one for top. The (only) use-case we've had in mind when supporting `threshold` is lazy-loading. I don't exactly see the use-case where you would need both offset and threshold, so I'm suggesting we keep it a little bit simpler and leave the `threshold` props out of it, and instead only support `offsetTop` and `offsetBottom`.

We can then allow percentages and numbers (interpreted as pixels). For the lazy-loading use-case, you would translate e.g. `threshold={0.5}` with `offsetTop='-50%'`. And to support the sticky navbar use-case, you'd use e.g. `offsetTop={50}` (assuming a 50px sticky navbar).

**Comment by jmeas** [comment]
Sounds like a plan to me!
